config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users

  get "test", to: "personality_tests#test", as: :test
  get "question_attempt", to: "personality_tests#question_attempt", as: :question_attempt

  resources :questions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/personality_score.rb
class PersonalityScore < ApplicationRecord
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :question_options, dependent: :destroy

  validates :body, presence: true
  accepts_nested_attributes_for :question_options, allow_destroy: true
end

app/models/question_option.rb
class QuestionOption < ApplicationRecord
  belongs_to :question
  validates :body, :personlity_type, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :personality_score, dependent: :destroy

  enum role: { user: 0, admin: 1 } 

  def check_personality
    introvert_score = self.personality_score.introvert_score
    extrovert_score = self.personality_score.extrovert_score

    introvert_score > extrovert_score ? "introvert" : "extrovert"
  end

  def admin?
    self.role == "admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/personality_tests_controller.rb
class PersonalityTestsController < ApplicationController
  def test
    personality_score = current_user.personality_score

    if personality_score.present?
      @question = Question.where.not(id: personality_score.attempted_question_ids).shuffle.sample
      @qeuestion_no = personality_score.attempted_question_ids.count + 1
    else
      @question = Question.all.shuffle.sample
      @qeuestion_no = 1
    end

  end

  def question_attempt
    personality_score = PersonalityScore.find_or_create_by(user_id: current_user.id)
    question = Question.where.not(id: personality_score.attempted_question_ids + [params[:question_id].to_i]).shuffle.sample
    option = QuestionOption.find(params[:option_id])

    introvert_score = option.personlity_type == "Extrovert" ? 1 : 0
    extrovert_score = option.personlity_type == "Introvert" ? 1 : 0

    personality_score.introvert_score = personality_score.introvert_score.to_i + introvert_score
    personality_score.extrovert_score = personality_score.extrovert_score.to_i + extrovert_score
    personality_score.attempted_question_ids << params[:question_id].to_i
    personality_score.save
    attempted_questions = personality_score.attempted_question_ids.count

    if attempted_questions >= 5
      render partial: 'result_page'
    else
      render partial: 'question', locals: {question: question, qeuestion_no: attempted_questions + 1}
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :check_ability

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
    4.times { @question.question_options.build}
  end

  def create
    @question = Question.new(question_params)
    if @question.save!
      redirect_to @question
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:body, question_options_attributes: [:body, :personlity_type])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def check_ability
    redirect_to root_path unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/personality_tests_helper.rb
module PersonalityTestsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/index.html.erb
<% if current_user.admin? %>
  <%= link_to "All Questios", questions_path, class: "btn btn-primary btn-lg" %>
<% end %>

<div class="container text-center main-div">
  <h1>Hello, Welcome to you our application</h1>
  <%= link_to "Stat Test", test_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Personality Test App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <nav class="navbar navbar-light">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Personality Test</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <%= link_to 'Edit profile', edit_user_registration_path, class: 'nav-item' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-item'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, class: 'nav-item'  %> |
            <%= link_to "Login", new_user_session_path, class: 'nav-item'  %>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/personality_tests/_question.html.erb
<div class="card question">
  <p>Question <%=  qeuestion_no %>/5</p>
  <p class="question-text"><%= question.body %></p>

  <% question.question_options.each_with_index do |option, index| %>
    <div class="options">
      <div class="question-option" data-question-id="<%= question.id %>" data-option-id="<%= option.id %>">
        <span>(<%= index + 1 %>)</span>
        <span class="question-option-text"><%= option.body %></span>
      </div>
    </div>
  <% end %>
  <div class="next-btn">
    <%= link_to "Next Question", "javascript:void(0)", class: "btn btn-primary btn-lg submit disabled" %>
  </div>
</div>

app/views/personality_tests/_result_page.html.erb
<div class="text-center">
  <h3>You are <%= current_user.check_personality %>!</h3>
  <br><br>

  <h1>Thank you!</h1>
</div>

app/views/personality_tests/test.html.erb
<div class="question-section">
  <% if @qeuestion_no > 5 %>
    <%= render "result_page"%>
  <% else %>
    <%= render "question", question: @question, qeuestion_no: @qeuestion_no %>
  <% end %>
</div>

app/views/questions/_form.html.erb
<%= form_with model: question, local: true do |form| %>
 <% if question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(question.errors.count, "error") %> prohibited
        this question from being saved:
      </h2>
      <ul>
        <% question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :Question %><br>
    <%= form.text_area :body, class: "form-control", rows: 3 %>
  </div>

  Question Options:
  <ul>
    <%= form.fields_for :question_options do |question_options_form| %>
      <li>
        <%= question_options_form.label :option %>
        <%= question_options_form.text_area :body, class: "form-control" %>
 
        <%= question_options_form.label :personlity_type %>
        <%= question_options_form.select :personlity_type, [['Extrovert', 'Extrovert'],['Introvert', 'Introvert'], ['Ambivert', 'Ambivert']] %>
      </li><br/>
    <% end %>
  </ul>
  
  <%= form.submit class: "btn btn-success" %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>
<%= render "form", question: @question %><br/>

<%= link_to "Back", questions_path, class: "btn btn-primary my-3" %>

app/views/questions/index.html.erb
<h1>All Questions</h1>
<%= link_to "Add Question", new_question_path, class: "btn btn-primary" %>
<br/><br/>

<% @questions.each_with_index do |question, index| %>
  <span><%= index + 1 %>.</span>
  <span><%= question.body %></span><br><br>

  <p>
  <%= link_to "Show", question_path(question), class: "btn btn-success" %>
  <%= link_to "Edit", edit_question_path(question), class: "btn btn-warning" %>
  <%= link_to "Delete", question_path(question), class: "btn btn-danger",
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
  </p>
  <hr/>
<% end %>

app/views/questions/new.html.erb
<h1>Add Question</h1>
<%= render "form", question: @question %><br>

<%= link_to "Back", questions_path, class: "btn btn-primary my-3" %>

app/views/questions/show.html.erb
<h1>Question</h1>
<hr/><br>
<h4><b>Question: </b><%= @question.body %><h4>

<%= link_to "Back", questions_path, class: "btn btn-primary my-3" %>